[build]
target = "xtensa-esp32-espidf"

[unstable]
build-std = ["std", "panic_abort"]

[target.xtensa-esp32-espidf]
linker = "ldproxy"
rustflags = ["--cfg", "espidf_time64"]

[env]
ESP_IDF_VERSION = "v5.2.2"
MCU = "esp32"
